#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <markdown file>"
  exit 10
fi

if [ ! -f "$1" ]; then
  echo "*** no such file: '$1'"
  exit 10
fi

pandoc -t plain "$1"| aspell --lang=en_GB --personal=./dictionary list | sort | uniq
